// ═══════════════════════════════════════════════════════════════════════════
// CertAnvil cert pack — Microsoft Azure AI Fundamentals, exam AI-901
// ═══════════════════════════════════════════════════════════════════════════
// v8.120.0 (2026-10-08): rebuilt for AI-901. Microsoft retired AI-900 on
// 2026-06-30 and replaced it with AI-901 (same credential name). The internal
// cert id stays 'ai900' so existing users' saved data and ai.certanvil.com
// keep working — see docs/superpowers/plans/2026-10-08-ai901-swap.md.
//
// Source of truth: the official AI-901 study guide, skills measured as of
// 2026-04-15 (learn.microsoft.com/credentials/certifications/resources/
// study-guides/ai-901). 2 domains / 7 skill groups. Microsoft does not number
// skill groups; X.Y below is their order within each domain.
//
// Legal: every exemplar is original, written from the public study guide and
// Microsoft Learn. Nothing is copied from paid question banks.

window.CERT_PACKS = window.CERT_PACKS || {};
window.CERT_PACKS.ai900 = {
  meta: {
    id: 'ai900',                // internal id kept from AI-900 (see header)
    name: 'Microsoft Azure AI Fundamentals',
    code: 'AI-901',
    blueprintUrl: 'https://learn.microsoft.com/credentials/certifications/resources/study-guides/ai-901',
    objectiveRanges: '1.1–1.3 (Identify AI concepts and capabilities), 2.1–2.4 (Implement AI solutions by using Microsoft Foundry) — Microsoft lists these skill groups unnumbered; X.Y is their order within each domain',
    examPassScore: 700,         // official: 700 on a 1000 scale
    examMaxScore: 1000,
    examQuestionCount: 45,      // not published by Microsoft — app mock format
    examTimeSeconds: 3600,      // not published by Microsoft — app mock format
  },
  // ── PRIORITY RETENTION CONCEPTS (AI-901) ─────────────────────────────────
  retentionGapConcepts: [
    {"label":"Six Responsible AI Principles","parentTopic":"Responsible AI Principles","objective":"1.1","keyword":"Microsoft names six: FAIRNESS (similar people, similar outcomes), RELIABILITY & SAFETY (works consistently and safely, including unexpected conditions), PRIVACY & SECURITY (protect data, control access), INCLUSIVENESS (usable and beneficial for people of all abilities and backgrounds), TRANSPARENCY (people can understand how it works and its limits), ACCOUNTABILITY (humans own and answer for the system). Scenario test: name the principle a situation supports or violates."},
    {"label":"Temperature vs Max Tokens vs System Prompt","parentTopic":"Model Deployment & Parameters","objective":"1.2","keyword":"TEMPERATURE = randomness (lower = more consistent, higher = more varied). MAX TOKENS = maximum response length, not quality. SYSTEM PROMPT = role, scope and rules for the conversation. Wrong-lever trap: raising max tokens does not make answers more accurate; lowering temperature does not restrict topics."},
    {"label":"Agent = Model + Instructions + Tools","parentTopic":"Building Single Agents in Foundry","objective":"2.1","keyword":"A Microsoft Foundry agent is a model, instructions (role, scope, what to refuse) and the tools it may call to act (for example searching knowledge or calling business functions). Single chat completion = one prompt in, one answer out. Multi-step work that takes actions = agent. Fix scope problems in the instructions first."},
    {"label":"Deployment Name in Foundry API Calls","parentTopic":"Foundry SDK Chat Clients","objective":"2.1","keyword":"Calling a model deployed in Foundry from Python: the model argument is the DEPLOYMENT NAME you chose; messages carry roles (system = behaviour, user = request); with the Chat Completions API the reply text is response.choices[0].message.content (the Responses API uses response.output_text). A model from the catalog must be deployed before an app can call it; the chat playground tests it with no code."},
    {"label":"Pick the Right Foundry Tool for the Workload","parentTopic":"Information Extraction Scenarios","objective":"1.3","keyword":"TEXT (sentiment, entities, key phrases, summarization, PII) = Azure Language. TRANSCRIPTION or SPOKEN OUTPUT as the end product = Azure Speech in Foundry Tools; a spoken question answered directly by one model = multimodal model with audio input. QUESTIONS ABOUT AN IMAGE or spoken prompts to one model = multimodal model. NEW IMAGES from a prompt = image generation model. STRUCTURED FIELDS from documents, images, audio or video = Azure Content Understanding with a field schema."},
    {"label":"Multimodal Model vs Dedicated Service","parentTopic":"Visual Input with Multimodal Models","objective":"2.3","keyword":"A multimodal model takes text plus images (and some take audio) in the same request and reasons over them, so the image goes in the user message next to the instruction. Choose a dedicated service when you need a specific, repeatable output: transcription (Speech), structured fields (Content Understanding), or text analytics (Language)."}
  ],

  // ── DOMAIN WEIGHTS — midpoints of the official ranges (40–45% / 55–60%) ──
  domainWeights: {
    'concepts': 0.425,
    'foundry': 0.575
  },

  domainLabels: {
    'concepts': 'Identify AI Concepts & Capabilities',
    'foundry': 'Implement AI Solutions with Microsoft Foundry'
  },

  // ── TOPIC → DOMAIN MAP (24 topics across the 7 official skill groups) ─────
  topicDomains: {
    'Responsible AI Principles': 'concepts',
    'Applying Responsible AI': 'concepts',
    'How Generative AI Models Work': 'concepts',
    'Choosing a Model': 'concepts',
    'Model Deployment & Parameters': 'concepts',
    'Generative & Agentic AI Scenarios': 'concepts',
    'Text Analysis Techniques': 'concepts',
    'Speech Recognition & Synthesis': 'concepts',
    'Computer Vision & Image Generation': 'concepts',
    'Information Extraction Scenarios': 'concepts',
    'Prompt Engineering (System & User Prompts)': 'foundry',
    'Deploying Models in the Foundry Portal': 'foundry',
    'Foundry SDK Chat Clients': 'foundry',
    'Building Single Agents in Foundry': 'foundry',
    'Agent Client Apps': 'foundry',
    'Text Analysis Apps in Foundry': 'foundry',
    'Speech Apps with Azure Speech': 'foundry',
    'Spoken Prompts with Multimodal Models': 'foundry',
    'Visual Input with Multimodal Models': 'foundry',
    'Image Generation with Generative Models': 'foundry',
    'Vision Apps in Foundry': 'foundry',
    'Content Understanding: Documents & Forms': 'foundry',
    'Content Understanding: Images, Audio & Video': 'foundry',
    'Information Extraction Apps': 'foundry'
  },

  // ── TOPIC RESOURCES — Microsoft Learn course for AI-901 + objective ──────
  topicResources: {
    'Responsible AI Principles': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.1', label: 'Responsible AI principles' },
    'Applying Responsible AI': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.1', label: 'Applying responsible AI' },
    'How Generative AI Models Work': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.2', label: 'How generative models work' },
    'Choosing a Model': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.2', label: 'Choosing a model' },
    'Model Deployment & Parameters': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.2', label: 'Deployment options & parameters' },
    'Generative & Agentic AI Scenarios': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.3', label: 'Generative & agentic scenarios' },
    'Text Analysis Techniques': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.3', label: 'Text analysis techniques' },
    'Speech Recognition & Synthesis': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.3', label: 'Speech recognition & synthesis' },
    'Computer Vision & Image Generation': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.3', label: 'Computer vision & image generation' },
    'Information Extraction Scenarios': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '1.3', label: 'Information extraction scenarios' },
    'Prompt Engineering (System & User Prompts)': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.1', label: 'System & user prompts' },
    'Deploying Models in the Foundry Portal': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.1', label: 'Deploying models in Foundry' },
    'Foundry SDK Chat Clients': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.1', label: 'Foundry SDK chat clients' },
    'Building Single Agents in Foundry': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.1', label: 'Building single agents' },
    'Agent Client Apps': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.1', label: 'Agent client apps' },
    'Text Analysis Apps in Foundry': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.2', label: 'Text analysis apps' },
    'Speech Apps with Azure Speech': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.2', label: 'Speech apps (Azure Speech)' },
    'Spoken Prompts with Multimodal Models': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.2', label: 'Spoken prompts (multimodal)' },
    'Visual Input with Multimodal Models': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.3', label: 'Visual input (multimodal)' },
    'Image Generation with Generative Models': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.3', label: 'Image generation' },
    'Vision Apps in Foundry': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.3', label: 'Vision apps' },
    'Content Understanding: Documents & Forms': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.4', label: 'Content Understanding: documents' },
    'Content Understanding: Images, Audio & Video': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.4', label: 'Content Understanding: media' },
    'Information Extraction Apps': { url: 'https://learn.microsoft.com/training/courses/ai-901t00', obj: '2.4', label: 'Information extraction apps' }
  },

  // ── QUESTION EXEMPLARS (AI-901) — few-shot style references for the
  // generator, never served as questions. House format, compact JSON.
  questionExemplars: [
    {"type":"mcq","question":"A hiring model consistently scores applicants from one university lower, even when their experience matches other candidates. Which Responsible AI principle is the main concern?","difficulty":"Exam Level","topic":"Responsible AI Principles","objective":"1.1","options":{"A":"Transparency","B":"Inclusiveness","C":"Fairness","D":"Reliability and safety"},"answer":"C","explanation":"Fairness means an AI system should treat people with similar qualifications in a similar way, so systematically lower scores for one group is a fairness problem. (A) Wrong — transparency is about being able to explain how the system reaches its outputs, not whether those outputs are equitable. (B) Wrong — inclusiveness is about designing AI that people of all abilities and backgrounds can use and benefit from. (D) Wrong — reliability and safety is about the system performing consistently and safely, including in unexpected conditions. Exam clue: unequal outcomes for comparable people = fairness.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A triage assistant tells clinicians when a recommendation rests on low-confidence input and describes what data the model was trained on. Which Responsible AI principle does this support MOST directly?","difficulty":"Exam Level","topic":"Responsible AI Principles","objective":"1.1","options":{"A":"Transparency","B":"Accountability","C":"Privacy and security","D":"Fairness"},"answer":"A","explanation":"Transparency means people should understand how an AI system works, what it was built from and where its limits are, which is exactly what disclosing confidence and training data does. (B) Wrong — accountability is about the people who design and deploy the system remaining answerable for it. (C) Wrong — privacy and security is about protecting personal data and controlling access to it. (D) Wrong — fairness is about equitable treatment across groups. Memory: explain it = transparency; own it = accountability.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A company launches a customer chatbot and names a team that reviews its incidents, signs off changes and answers for its decisions. Which Responsible AI principle is that team putting into practice?","difficulty":"Foundational","topic":"Applying Responsible AI","objective":"1.1","options":{"A":"Inclusiveness","B":"Transparency","C":"Reliability and safety","D":"Accountability"},"answer":"D","explanation":"Accountability means humans stay responsible for AI systems, with clear ownership, review and governance, which is what a named oversight team provides. (A) Wrong — inclusiveness is about making the system usable and beneficial for people of all abilities and backgrounds. (B) Wrong — transparency is about explaining how the system works and its limitations. (C) Wrong — reliability and safety is about consistent, safe operation, not who answers for it. Exam clue: a person or team who owns and answers for the AI = accountability.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"At a high level, how does a large language model produce a response to a prompt?","difficulty":"Foundational","topic":"How Generative AI Models Work","objective":"1.2","options":{"A":"It looks up the closest matching web page and returns that page word for word","B":"It repeatedly predicts the next token based on the prompt and the text so far","C":"It picks a pre-written answer from a database of approved responses","D":"It follows a fixed set of rules that developers wrote for each kind of question"},"answer":"B","explanation":"A large language model generates text one token at a time, each time predicting a likely next token from the prompt and everything it has produced so far. (A) Wrong — generation itself is token prediction; a solution can add search as a tool, but the model does not simply return a web page. (C) Wrong — returning stored answers describes a FAQ lookup system, not a generative model. (D) Wrong — hand-written rules describe a rule-based system, which is the opposite of a learned model. Memory: LLM = next-token prediction.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"What are embeddings used for in generative AI solutions?","difficulty":"Exam Level","topic":"How Generative AI Models Work","objective":"1.2","options":{"A":"Encrypting prompts before they leave the client application","B":"Capping how many tokens a model can return in one response","C":"Turning text into number vectors so similar meanings sit close together","D":"Shrinking a large model so that it can run on mobile devices"},"answer":"C","explanation":"Embeddings represent text as numeric vectors in which items with similar meaning are close together, which powers semantic search and retrieval for grounding. (A) Wrong — encryption is a security control and is unrelated to embeddings. (B) Wrong — the response length limit is the max tokens setting. (D) Wrong — making a model smaller is model compression or choosing a smaller model, not embeddings. Exam clue: similar meaning + numeric vectors + semantic search = embeddings.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A team needs a model that can answer questions about photos customers upload as well as their written questions. What should they look for in the Microsoft Foundry model catalog?","difficulty":"Exam Level","topic":"Choosing a Model","objective":"1.2","options":{"A":"A multimodal model that accepts both image and text input","B":"The text-only model with the largest context window available","C":"An embeddings model that turns each photo into a vector","D":"A speech to text model that transcribes the customer question"},"answer":"A","explanation":"Answering questions about images needs a multimodal model that can take image and text input in the same request. (B) Wrong — a large context window does not let a text-only model see images. (C) Wrong — an embeddings model produces vectors for search; it does not answer questions. (D) Wrong — speech to text converts audio to text and does not interpret photos. Exam clue: images + text in one question = multimodal model.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A chat app gives very varied, creative answers, but the business wants responses that are more consistent and predictable. Which change helps MOST?","difficulty":"Exam Level","topic":"Model Deployment & Parameters","objective":"1.2","options":{"A":"Raise the max tokens value for every response","B":"Add creative writing examples to the system prompt","C":"Move the deployment to a different Azure region","D":"Lower the temperature"},"answer":"D","explanation":"Temperature controls how random the model's choices are; lowering it makes responses more focused and repeatable. (A) Wrong — max tokens only limits how long a response can be. (B) Wrong — creative examples would push the output towards more variety, not less. (C) Wrong — region affects latency and data location, not how varied the answers are. Memory: temperature is the randomness dial.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A developer wants to use a model from Microsoft Foundry without managing any virtual machines, paying only for the tokens they use. Which deployment approach fits?","difficulty":"Exam Level","topic":"Model Deployment & Parameters","objective":"1.2","options":{"A":"A managed compute deployment on dedicated virtual machines","B":"A serverless (standard) deployment hosted by Azure","C":"Copying the model files to run on a local laptop instead","D":"Provisioning and running a Kubernetes cluster for the model"},"answer":"B","explanation":"A serverless deployment (Foundry labels these Standard or Global Standard) is hosted by Azure and billed for the tokens used, with no infrastructure to manage. (A) Wrong — managed compute runs the model on dedicated virtual machines that you size and pay for while they run. (C) Wrong — running the model on your own laptop means providing and managing the hardware yourself, and it does not give you a hosted endpoint billed per token. (D) Wrong — a Kubernetes cluster is infrastructure you would have to operate. Exam clue: no infrastructure + pay per token = serverless deployment.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Which scenario is the BEST fit for an AI agent rather than a single chat completion?","difficulty":"Exam Level","topic":"Generative & Agentic AI Scenarios","objective":"1.3","options":{"A":"Translating one product description into French for a website","B":"Writing a short poem to open a marketing email campaign","C":"Checking an order, booking a courier and emailing the customer","D":"Summarising the transcript of one team meeting into bullets"},"answer":"C","explanation":"An agent combines a model with instructions and tools so it can carry out multi-step tasks, such as checking an order, booking a courier and sending an email. (A) Wrong — a single translation is one generation request. (B) Wrong — writing a poem is one generation request with no actions to take. (D) Wrong — summarising one transcript is a single prompt and response. Exam clue: several steps + using business tools to act = agent.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"multi-select","question":"(Choose TWO) A retailer wants to find the products and places mentioned in customer reviews and decide whether each review is positive or negative. Which TWO text analysis techniques does this need?","difficulty":"Exam Level","topic":"Text Analysis Techniques","objective":"1.3","options":{"A":"Speech synthesis","B":"Named entity recognition","C":"Image generation","D":"Sentiment analysis","E":"Optical character recognition"},"answers":["B","D"],"explanation":"Named entity recognition (entity detection) finds named items such as products and places, and sentiment analysis judges whether text is positive, negative or neutral. (A) Wrong — speech synthesis turns text into spoken audio. (C) Wrong — image generation creates pictures from prompts. (E) Wrong — optical character recognition reads text from images, but these reviews are already text. Exam clue: what is mentioned = entities; how the writer feels = sentiment.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A support team wants a short overview of each long customer email so agents can triage faster. Which text analysis technique fits?","difficulty":"Foundational","topic":"Text Analysis Techniques","objective":"1.3","options":{"A":"Summarization","B":"Key phrase extraction","C":"Language detection","D":"Entity detection"},"answer":"A","explanation":"Summarization condenses a long text into a short version that keeps the main points. (B) Wrong — key phrase extraction returns a list of important phrases, not a readable overview. (C) Wrong — language detection only identifies which language the email is written in. (D) Wrong — entity detection lists named items such as people, products or dates. Exam clue: a short readable version of long text = summarization.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A bank wants its phone line to read out account balances in a natural-sounding voice. Which capability is needed?","difficulty":"Foundational","topic":"Speech Recognition & Synthesis","objective":"1.3","options":{"A":"Speech recognition (speech to text)","B":"Sentiment analysis of the caller","C":"Keyword extraction from transcripts","D":"Speech synthesis (text to speech)"},"answer":"D","explanation":"Speech synthesis converts text, such as a balance, into spoken audio. (A) Wrong — speech recognition goes the other way, turning spoken words into text. (B) Wrong — sentiment analysis judges emotion in text and produces no audio. (C) Wrong — keyword extraction pulls key words out of text and produces no audio. Memory: synthesis speaks; recognition listens.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A marketing team wants to create new product images from a written description rather than analyse existing photos. Which type of AI workload is this?","difficulty":"Foundational","topic":"Computer Vision & Image Generation","objective":"1.3","options":{"A":"Object detection in existing photos","B":"Image generation","C":"Optical character recognition","D":"Image classification of a catalogue"},"answer":"B","explanation":"Creating new pictures from a text description is image generation, a generative AI workload. (A) Wrong — object detection locates items inside existing images. (C) Wrong — optical character recognition reads text from images. (D) Wrong — image classification labels what an existing image shows. Exam clue: new image from a prompt = image generation; analysing an image = computer vision.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"An insurer receives thousands of scanned claim forms and wants the claim number, date and amount copied into a database automatically. Which AI workload is this?","difficulty":"Exam Level","topic":"Information Extraction Scenarios","objective":"1.3","options":{"A":"Image generation","B":"Sentiment analysis","C":"Information extraction","D":"Speech synthesis"},"answer":"C","explanation":"Pulling specific fields out of documents into structured data is information extraction. (A) Wrong — image generation creates new images rather than reading existing ones. (B) Wrong — sentiment analysis judges opinion and returns no field values. (D) Wrong — speech synthesis produces spoken audio from text. Exam clue: named fields from forms into a database = information extraction.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"In a chat app built on a Microsoft Foundry model, where should the developer state that the assistant must only answer questions about the company travel policy?","difficulty":"Foundational","topic":"Prompt Engineering (System & User Prompts)","objective":"2.1","options":{"A":"In the system prompt","B":"In every prompt the employee types","C":"In the temperature setting","D":"In the deployment region"},"answer":"A","explanation":"The system prompt sets the assistant's role, scope and rules for the whole conversation. (B) Wrong — user prompts are the employee's own requests and should not have to repeat the rules. (C) Wrong — temperature controls randomness, not what topics are allowed. (D) Wrong — the region decides where the model runs, not how it behaves. Memory: system prompt = the rules; user prompt = the request.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A model's answers about refund rules are vague. Which change to the prompt is MOST likely to make them specific?","difficulty":"Exam Level","topic":"Prompt Engineering (System & User Prompts)","objective":"2.1","options":{"A":"Ask the same question three times in one message","B":"Remove the system prompt so it has fewer limits","C":"Include the refund policy text and the answer format","D":"Set max tokens to the highest allowed value"},"answer":"C","explanation":"Giving the model the relevant policy text and a clear format grounds its answer in the facts and shapes the output. (A) Wrong — repeating the question adds no new information. (B) Wrong — removing the system prompt takes away guidance and usually makes answers less focused. (D) Wrong — a higher max tokens allows longer answers but does not make them more accurate. Exam clue: vague answers = give context and explicit instructions.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"In the Microsoft Foundry portal, what is needed before a chat app can send prompts to a model from the catalog?","difficulty":"Foundational","topic":"Deploying Models in the Foundry Portal","objective":"2.1","options":{"A":"Fine-tune the model on company data first","B":"Deploy the model so it has an endpoint to call","C":"Download the model weights to the app server","D":"Convert it into an embeddings model first"},"answer":"B","explanation":"Deploying a model in Foundry creates a named deployment that an app calls through the resource's endpoint. (A) Wrong — fine-tuning is optional and is not needed just to send prompts. (C) Wrong — the app calls the hosted deployment over the network instead of running the weights itself. (D) Wrong — an embeddings model produces vectors and cannot hold a chat. Exam clue: catalog model to usable endpoint = deploy it.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"After deploying a model in the Microsoft Foundry portal, a developer wants to try prompts and adjust parameters before writing any code. Where can they do this?","difficulty":"Foundational","topic":"Deploying Models in the Foundry Portal","objective":"2.1","options":{"A":"In Azure Cost Management reports","B":"In the model training dataset","C":"In the Azure Monitor alert rules","D":"In the portal chat playground"},"answer":"D","explanation":"The chat playground in the Foundry portal lets you send prompts to a deployment, edit the system message and tune parameters such as temperature without code. (A) Wrong — Cost Management shows spending, not model responses. (B) Wrong — a training dataset is for fine-tuning and cannot be used to chat. (C) Wrong — Azure Monitor alerts track metrics and do not send prompts. Exam clue: try prompts with no code = playground.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A developer calls a model deployed in Microsoft Foundry with this Python code:\n\nresponse = client.chat.completions.create(\n    model=\"support-gpt\",\n    messages=[\n        {\"role\": \"system\", \"content\": \"Answer in one sentence.\"},\n        {\"role\": \"user\", \"content\": \"How do I reset my password?\"}\n    ]\n)\n\nWhat does \"support-gpt\" refer to?","difficulty":"Exam Level","topic":"Foundry SDK Chat Clients","objective":"2.1","options":{"A":"The name of the model deployment","B":"The name of the signed-in user","C":"The title of the system prompt","D":"The Azure region of the endpoint"},"answer":"A","explanation":"When calling a model deployed in Azure, the model argument is the deployment name chosen when the model was deployed. (B) Wrong — this call passes no user identity in the model argument. (C) Wrong — the system prompt is the message whose role is system. (D) Wrong — the region is part of the endpoint configuration, not this argument. Exam clue: model= in a Foundry chat call = your deployment name.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"In this Python code, which part sets how the assistant behaves for the whole conversation?\n\nresponse = client.chat.completions.create(\n    model=\"support-gpt\",\n    messages=[\n        {\"role\": \"system\", \"content\": \"Answer in one sentence.\"},\n        {\"role\": \"user\", \"content\": \"How do I reset my password?\"}\n    ]\n)","difficulty":"Exam Level","topic":"Foundry SDK Chat Clients","objective":"2.1","options":{"A":"The message whose role is user","B":"The model=\"support-gpt\" argument","C":"The message whose role is system","D":"The variable named response"},"answer":"C","explanation":"The system message, here asking for one-sentence answers, sets the assistant's behaviour for the conversation. (A) Wrong — the user message is the question being asked. (B) Wrong — the model argument selects which deployment answers. (D) Wrong — response simply holds what the model sends back. Memory: role system = behaviour; role user = request.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"After this Python call, which expression returns the text of the model's reply?\n\nresponse = client.chat.completions.create(model=\"support-gpt\", messages=msgs)","difficulty":"Hard","topic":"Foundry SDK Chat Clients","objective":"2.1","options":{"A":"response.messages[0][\"content\"]","B":"response.choices[0].message.content","C":"response.usage.completion_tokens","D":"msgs[len(msgs) - 1][\"content\"]"},"answer":"B","explanation":"A chat completion returns a list of choices, and the reply text is in the first choice's message content. (A) Wrong — the reply is returned in choices, not as a messages list on the response. (C) Wrong — usage reports how many tokens were used, not the reply text. (D) Wrong — msgs[len(msgs) - 1] is the last message the app sent, not the model's answer. Memory: choices[0].message.content.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"When creating an agent in Microsoft Foundry, which combination defines what the agent is and what it can do?","difficulty":"Exam Level","topic":"Building Single Agents in Foundry","objective":"2.1","options":{"A":"A model, instructions and the tools it may use","B":"A training set, a test set and an accuracy target","C":"A virtual network, a firewall and a public IP","D":"A storage account, a container and a policy"},"answer":"A","explanation":"A Foundry agent is defined by the model it uses, the instructions that set its role and limits, and the tools it is allowed to call. (B) Wrong — training and test sets with an accuracy target describe training a model, not configuring an agent. (C) Wrong — networking settings control connectivity, not the agent's behaviour. (D) Wrong — storage settings hold data but do not define an agent. Memory: agent = model + instructions + tools.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"An HR agent keeps answering questions about individual salaries, which it should decline. What should be changed FIRST?","difficulty":"Exam Level","topic":"Building Single Agents in Foundry","objective":"2.1","options":{"A":"Switch the agent to a bigger model","B":"Give the agent more tools to call","C":"Increase the max tokens for answers","D":"Update its instructions to decline these"},"answer":"D","explanation":"An agent's instructions set its scope and what it must refuse, so stating that salary questions are out of scope is the first fix. (A) Wrong — a bigger model is more capable but does not by itself narrow what the agent answers. (B) Wrong — more tools extend what the agent can do instead of restricting it. (C) Wrong — max tokens only limits answer length. Exam clue: wrong scope or behaviour = fix the instructions.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A lightweight client app talks to a Microsoft Foundry agent. Why does it send each new message in the same conversation instead of starting a new one each time?","difficulty":"Exam Level","topic":"Agent Client Apps","objective":"2.1","options":{"A":"It lowers the temperature the agent uses","B":"It deploys a new model version on each turn","C":"It lets the agent use earlier messages as context","D":"It is needed before the agent can call a tool"},"answer":"C","explanation":"Keeping the conversation lets the agent use earlier messages as context, so follow-up questions such as 'and what about next week?' make sense. (A) Wrong — temperature is a model setting and is not changed by reusing a conversation. (B) Wrong — reusing a conversation does not deploy anything. (D) Wrong — an agent can call tools within a new conversation too. Exam clue: follow-ups that depend on earlier turns = reuse the conversation.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A developer builds an app that must flag customer messages containing personal data, such as phone numbers, before they are stored. Which Azure Language capability fits?","difficulty":"Exam Level","topic":"Text Analysis Apps in Foundry","objective":"2.2","options":{"A":"Key phrase extraction","B":"PII detection","C":"Language detection","D":"Summarization"},"answer":"B","explanation":"PII detection identifies personal data such as phone numbers, emails and addresses in text so it can be flagged or redacted. (A) Wrong — key phrase extraction lists the main topics, not personal data. (C) Wrong — language detection only identifies which language is used. (D) Wrong — summarization shortens the text and would not reliably flag personal data. Exam clue: find or redact personal data = PII detection.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"An app built with Azure Speech in Foundry Tools must turn a caller's spoken words into text so the calls can be searched later. Which feature is used?","difficulty":"Foundational","topic":"Speech Apps with Azure Speech","objective":"2.2","options":{"A":"Speech to text","B":"Text to speech","C":"Speech translation","D":"Custom voice"},"answer":"A","explanation":"Speech to text transcribes spoken audio into written text that can be stored and searched. (B) Wrong — text to speech turns text into audio, the opposite direction. (C) Wrong — speech translation converts speech into another language, which is not required here. (D) Wrong — a custom voice creates a branded synthetic voice for text to speech. Memory: callers to searchable text = speech to text.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A team wants users to ask questions out loud and get answers from a single deployed model, without building a separate speech to text step. What kind of model do they need?","difficulty":"Exam Level","topic":"Spoken Prompts with Multimodal Models","objective":"2.2","options":{"A":"An embeddings model for the questions","B":"A text-only chat completions model","C":"An image generation model","D":"A multimodal model with audio input"},"answer":"D","explanation":"A multimodal model that accepts audio input can take the spoken question directly and respond. (A) Wrong — an embeddings model turns input into vectors and does not answer questions. (B) Wrong — a text-only model would need the audio transcribed first. (C) Wrong — an image generation model creates pictures, not answers. Exam clue: spoken prompt to one model with no transcription step = multimodal with audio input.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A customer uploads a photo of a damaged parcel and asks a chat app whether the box looks damaged enough to claim a refund. How can a Microsoft Foundry solution answer?","difficulty":"Exam Level","topic":"Visual Input with Multimodal Models","objective":"2.3","options":{"A":"Send only the typed question to a text-only model","B":"Run OCR on the photo and then discard the image","C":"Send the photo and the question to a multimodal model","D":"Use speech synthesis to describe the photo aloud"},"answer":"C","explanation":"A multimodal model can look at the image and the question together and reason about the damage. (A) Wrong — without the photo a text-only model has nothing to judge. (B) Wrong — OCR only reads text in the image and would miss the visible damage. (D) Wrong — speech synthesis produces audio and cannot analyse a picture. Exam clue: question about what a picture shows = multimodal model with the image as input.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A developer uses a generative image model in Microsoft Foundry. What input defines the picture it creates?","difficulty":"Foundational","topic":"Image Generation with Generative Models","objective":"2.3","options":{"A":"A labelled set of training photos","B":"A text prompt describing the image","C":"A bounding box drawn on another image","D":"An audio recording of the request"},"answer":"B","explanation":"Image generation models create pictures mainly from a text prompt describing what to draw. (A) Wrong — labelled training photos are used to train or tune vision models, not to request one image. (C) Wrong — bounding boxes mark objects for detection tasks. (D) Wrong — image generation models are driven by a written prompt, not an audio recording. Memory: describe it in words, get a picture.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A lightweight vision app sends shelf photos to a deployed multimodal model and asks it to list out-of-stock products. Where does the app put the photo?","difficulty":"Exam Level","topic":"Vision Apps in Foundry","objective":"2.3","options":{"A":"In the user message, with the text instruction","B":"In a separate request to a speech endpoint","C":"In the deployment name used for the call","D":"In the training data the model learned from"},"answer":"A","explanation":"With a multimodal chat model, the image goes into the user message as image content alongside the text instruction. (B) Wrong — a speech endpoint processes audio, not photos. (C) Wrong — the deployment name only selects which model answers. (D) Wrong — training data is what the model learned from; it cannot carry a new photo at request time. Exam clue: image plus instruction in the same user message = multimodal input.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A finance team wants the invoice number, supplier and total pulled from PDF invoices into structured fields. Which Foundry tool is designed for this?","difficulty":"Exam Level","topic":"Content Understanding: Documents & Forms","objective":"2.4","options":{"A":"Azure Speech","B":"An image generation model","C":"Azure Content Understanding","D":"Azure Language sentiment analysis"},"answer":"C","explanation":"Azure Content Understanding analyses documents and returns the fields you define, such as invoice number, supplier and total, as structured output. (A) Wrong — Azure Speech works with audio. (B) Wrong — an image generation model creates new images and does not read invoices. (D) Wrong — sentiment analysis judges opinion and returns no invoice fields. Exam clue: fields from documents or forms = Content Understanding.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A media company wants topics, speaker statements and timestamps extracted from recorded webinars into a searchable format. What should they use?","difficulty":"Exam Level","topic":"Content Understanding: Images, Audio & Video","objective":"2.4","options":{"A":"Text to speech for each webinar recording","B":"An embeddings model on its own","C":"Image classification of the video frames","D":"Content Understanding on the audio and video"},"answer":"D","explanation":"Content Understanding can analyse audio and video and return structured information such as transcripts, topics and timestamps. (A) Wrong — text to speech generates audio rather than analysing it. (B) Wrong — embeddings help search existing text but do not extract it from recordings. (C) Wrong — image classification labels still images and cannot capture speech or timing. Exam clue: structured data from audio or video = Content Understanding.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"When building an extraction app with Content Understanding, what does defining a field schema, for example InvoiceTotal as a number, control?","difficulty":"Hard","topic":"Information Extraction Apps","objective":"2.4","options":{"A":"How long the app waits for the analyzer","B":"Which fields come back, and their data types","C":"Which Azure region stores the uploaded file","D":"Which chat deployment the app calls"},"answer":"B","explanation":"A field schema tells the analyzer which fields to extract and what type each should be, so the output is predictable structured data. (A) Wrong — wait time is an app or timeout setting, not part of the schema. (C) Wrong — storage region is set by the resource, not the field schema. (D) Wrong — the field schema defines output fields, not which chat deployment the app calls. Memory: schema = what you get back and in what shape.","source":"curated-ai901-p1","addedVersion":"8.120.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A support chatbot stores customers' full card numbers in its conversation logs. Which Responsible AI principle is MOST at risk?","difficulty":"Foundational","topic":"Responsible AI Principles","objective":"1.1","options":{"A":"Accountability","B":"Privacy and security","C":"Transparency","D":"Inclusiveness"},"answer":"B","explanation":"Privacy and security is about protecting personal data and controlling who can access it, and storing full card numbers in logs exposes exactly that data. (A) Wrong — accountability is about people owning and answering for the system, not how its data is protected. (C) Wrong — transparency is about explaining how the system works and its limits. (D) Wrong — inclusiveness is about the system being usable and beneficial for people of all abilities and backgrounds. Exam clue: personal data exposed or poorly protected = privacy and security.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A dosing assistant gives correct answers in testing but suggests wrong doses when a nurse enters a weight in pounds instead of kilograms. Which principle does testing for this kind of unexpected input address?","difficulty":"Exam Level","topic":"Responsible AI Principles","objective":"1.1","options":{"A":"Fairness","B":"Inclusiveness","C":"Transparency","D":"Reliability and safety"},"answer":"D","explanation":"Reliability and safety means a system should behave safely and consistently, including when it receives unexpected or unusual input. (A) Wrong — fairness is about similar people receiving similar outcomes, not handling unexpected input. (B) Wrong — inclusiveness is about designing for people of all abilities and backgrounds. (C) Wrong — transparency is about explaining how the system reaches its outputs. Memory: works safely when things go wrong or look unusual = reliability and safety.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Before launch, a team deliberately tries to push its generative AI app into producing harmful content, then records how often it succeeds. What are they doing?","difficulty":"Exam Level","topic":"Applying Responsible AI","objective":"1.1","options":{"A":"Identifying and measuring potential harms","B":"Fine-tuning the model so that it replies faster","C":"Choosing a cheaper deployment option","D":"Increasing the model's context window"},"answer":"A","explanation":"Testing an app adversarially and counting failures identifies the harms it could cause and measures how often they occur, which comes before choosing mitigations. (B) Wrong — fine-tuning adapts a model with training data and is unrelated to probing for harms. (C) Wrong — deployment choice affects cost and capacity, not harm testing. (D) Wrong — a larger context window lets the model read more text but tests nothing. Exam clue: probing an app for harmful output before launch = identify and measure harms.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Which action BEST helps users rely appropriately on answers from an AI assistant?","difficulty":"Foundational","topic":"Applying Responsible AI","objective":"1.1","options":{"A":"Hiding the fact that the answers are generated by AI","B":"Removing every human review step from the process","C":"Telling users the answers are AI-generated and may contain mistakes","D":"Raising the temperature so that the answers sound more natural and varied"},"answer":"C","explanation":"Disclosing that content is AI-generated and can be wrong supports transparency and helps users decide how much to trust it. (A) Wrong — hiding AI involvement undermines transparency and appropriate trust. (B) Wrong — removing human oversight weakens accountability and safety. (D) Wrong — temperature changes randomness and does nothing to help users judge reliability. Memory: tell people it's AI and that it can be wrong = transparency.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Why can a generative model state something confidently that turns out to be false?","difficulty":"Exam Level","topic":"How Generative AI Models Work","objective":"1.2","options":{"A":"It copies its answers only from verified databases","B":"It inserts errors on purpose to save on tokens","C":"It predicts likely text instead of checking facts","D":"It has run out of space in its context window for the facts"},"answer":"C","explanation":"A language model generates plausible next tokens; unless it is grounded in trusted data, nothing in that process verifies the facts. (A) Wrong — a base model generates text instead of copying from verified sources. (B) Wrong — models have no mechanism to add errors deliberately. (D) Wrong — a full context window limits how much text is considered; it is not why confident errors occur. Exam clue: confident but wrong output = hallucination; reduce it by grounding the prompt in trusted data.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"What does a model's context window describe?","difficulty":"Foundational","topic":"How Generative AI Models Work","objective":"1.2","options":{"A":"The most tokens it can consider in one request","B":"How long the model stays deployed before it expires","C":"How many users can call the model at the same time","D":"The size of the chat area shown in the playground"},"answer":"A","explanation":"The context window is the token limit a model can consider at once, covering the prompt, any history and the reply. (B) Wrong — deployment lifetime is unrelated to the context window. (C) Wrong — concurrent usage is a capacity or quota matter. (D) Wrong — the playground's layout has nothing to do with the model's limits. Memory: context window = how much text the model can 'see' in one go.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A team is choosing between several catalog models for a document summarisation app. What is the MOST reliable way to compare them?","difficulty":"Exam Level","topic":"Choosing a Model","objective":"1.2","options":{"A":"Pick whichever model has the newest release date","B":"Choose the model that offers the largest context window available","C":"Choose the model with the most popular name","D":"Test each on sample app documents with the same prompts"},"answer":"D","explanation":"Testing candidate models on representative data with identical prompts shows which performs best for this task. (A) Wrong — a newer model is not automatically better for a specific task. (B) Wrong — context size matters only if the documents need it; it says nothing about summary quality. (C) Wrong — popularity is not evidence of performance on your data. Exam clue: compare models on your own task and data, with the same prompts.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Which type of model should power semantic search across thousands of policy documents?","difficulty":"Foundational","topic":"Choosing a Model","objective":"1.2","options":{"A":"An image generation model","B":"An embeddings model","C":"A text to speech model","D":"A speech to text model"},"answer":"B","explanation":"Embeddings models turn text into vectors so that passages with similar meaning can be found, which is the basis of semantic search. (A) Wrong — image generation creates pictures and cannot search text. (C) Wrong — text to speech produces audio. (D) Wrong — speech to text transcribes audio and does not search documents. Memory: search by meaning = embeddings.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A legal firm needs careful multi-step reasoning about long contracts and accepts slower, more expensive responses. Which choice fits BEST?","difficulty":"Hard","topic":"Choosing a Model","objective":"1.2","options":{"A":"The smallest and fastest model available in the catalog","B":"A larger, more capable model","C":"An embeddings model on its own","D":"An image generation model"},"answer":"B","explanation":"Complex reasoning over long documents favours a more capable model, and the firm has accepted the extra cost and latency. (A) Wrong — small models trade reasoning ability for speed and cost, which is the wrong trade here. (C) Wrong — embeddings support search but do not reason or write answers. (D) Wrong — image models create pictures and cannot analyse contracts. Exam clue: hard reasoning and quality over cost = larger, more capable model.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"What does lowering top-p do to a model's output?","difficulty":"Hard","topic":"Model Deployment & Parameters","objective":"1.2","options":{"A":"It shortens every reply so it uses fewer tokens overall","B":"It forces the model to answer only in English","C":"It makes the model deploy faster","D":"It keeps word choices to the likeliest options"},"answer":"D","explanation":"Top-p restricts sampling to the smallest set of tokens whose probabilities add up to p, so a lower value keeps choices to the most likely words. (A) Wrong — reply length is limited by max tokens. (B) Wrong — language is controlled by the prompt and model, not top-p. (C) Wrong — top-p is a generation setting with no effect on deployment. Memory: temperature and top-p both tune randomness; max tokens tunes length.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A high-traffic production app needs reserved, predictable model capacity rather than paying per token. Which deployment approach fits?","difficulty":"Exam Level","topic":"Model Deployment & Parameters","objective":"1.2","options":{"A":"A provisioned throughput deployment","B":"A serverless pay-per-token deployment","C":"Running the prompts by hand in the playground","D":"Choosing a model with a smaller context window"},"answer":"A","explanation":"Provisioned throughput reserves model capacity for predictable performance at high volume, billed for the capacity rather than per token. (B) Wrong — pay-per-token suits variable use but doesn't reserve capacity. (C) Wrong — the playground is for testing, not production traffic. (D) Wrong — context window size does not reserve capacity. Exam clue: predictable capacity for heavy production load = provisioned throughput.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A model keeps repeating the same phrases in long answers. Which parameter is designed to reduce this?","difficulty":"Exam Level","topic":"Model Deployment & Parameters","objective":"1.2","options":{"A":"Max tokens","B":"The deployment name","C":"Frequency penalty","D":"The API version"},"answer":"C","explanation":"A frequency penalty lowers the chance of reusing tokens that have already appeared, which reduces repetition. (A) Wrong — max tokens only limits how long a reply can be. (B) Wrong — the deployment name selects which model answers. (D) Wrong — the API version controls which API features are available. Memory: repeating itself = frequency penalty; too long = max tokens.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Which of these is a generative AI workload?","difficulty":"Foundational","topic":"Generative & Agentic AI Scenarios","objective":"1.3","options":{"A":"Sorting invoices by date in a spreadsheet","B":"Counting the rows in a database table","C":"Drafting a product description from a few bullet points","D":"Blocking network traffic coming from a known malicious address"},"answer":"C","explanation":"Creating new text from a short brief is generative AI. (A) Wrong — sorting is a deterministic data task. (B) Wrong — counting rows is a simple query. (D) Wrong — blocking traffic is a firewall rule. Exam clue: creates new content (text, images, code) = generative AI.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"What distinguishes an AI agent from a basic chatbot?","difficulty":"Exam Level","topic":"Generative & Agentic AI Scenarios","objective":"1.3","options":{"A":"It can plan steps and use tools to take actions towards a goal","B":"It answers only one question per session and then has to restart","C":"It works without any language model at all","D":"It can only work with images, never text"},"answer":"A","explanation":"Agents pair a model with instructions and tools, so they can work through tasks and act on systems instead of only replying. (B) Wrong — agents commonly keep conversations going across turns. (C) Wrong — agents in Foundry are built on a model. (D) Wrong — agents work with text and can use multimodal models too. Memory: chatbot replies; agent reasons, uses tools and acts.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A news site wants each article tagged with the companies and people it mentions. Which technique fits?","difficulty":"Foundational","topic":"Text Analysis Techniques","objective":"1.3","options":{"A":"Sentiment analysis","B":"Speech synthesis","C":"Image classification of photos","D":"Named entity recognition"},"answer":"D","explanation":"Named entity recognition finds and categorises named items such as people, organisations and places in text. (A) Wrong — sentiment analysis judges opinion, not who is mentioned. (B) Wrong — speech synthesis produces audio. (C) Wrong — image classification labels pictures, not text. Exam clue: who or what is mentioned = named entity recognition.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Which pairing of speech capabilities is correct?","difficulty":"Foundational","topic":"Speech Recognition & Synthesis","objective":"1.3","options":{"A":"Speech to text produces audio; text to speech transcribes audio","B":"Speech to text transcribes audio; text to speech speaks text","C":"Both capabilities only translate between languages","D":"Both capabilities only identify who is speaking"},"answer":"B","explanation":"Speech recognition (speech to text) turns spoken words into text, and speech synthesis (text to speech) turns text into speech. (A) Wrong — this reverses the two capabilities. (C) Wrong — translation is a separate capability. (D) Wrong — telling speakers apart is speaker diarization, a separate feature. Memory: name says the direction — speech to text, text to speech.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A warehouse wants to find and count every pallet in a camera image, with a box drawn around each one. Which computer vision task is this?","difficulty":"Exam Level","topic":"Computer Vision & Image Generation","objective":"1.3","options":{"A":"Image classification","B":"Object detection","C":"Optical character recognition","D":"Image generation"},"answer":"B","explanation":"Object detection locates each object in an image and returns its position, typically as a bounding box. (A) Wrong — image classification labels the whole image without locating items. (C) Wrong — OCR reads text in an image. (D) Wrong — image generation creates new images rather than analysing them. Exam clue: where is each object (boxes) = object detection.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Which scenario is information extraction rather than summarization?","difficulty":"Exam Level","topic":"Information Extraction Scenarios","objective":"1.3","options":{"A":"Writing a short three-line overview of a long annual report","B":"Rewriting an email in a friendlier tone","C":"Creating an image to illustrate a blog post","D":"Pulling policy numbers and dates from letters"},"answer":"D","explanation":"Extracting specific named values into fields is information extraction. (A) Wrong — condensing text is summarization. (B) Wrong — rewriting is text generation. (C) Wrong — creating images is image generation. Exam clue: specific fields out of content = extraction; shorter version = summarization.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A dashboard needs a model to return consistent JSON every time. Which prompt change helps MOST?","difficulty":"Exam Level","topic":"Prompt Engineering (System & User Prompts)","objective":"2.1","options":{"A":"Name the exact JSON fields and show an example","B":"Ask the model to be creative with the layout of each answer","C":"Raise the temperature so the output varies","D":"Remove the system message entirely"},"answer":"A","explanation":"Specifying the format and showing an example gives the model a clear pattern to follow, which makes structured output more consistent. (B) Wrong — asking for creativity encourages variation. (C) Wrong — higher temperature makes output less consistent. (D) Wrong — removing instructions gives the model less guidance. Memory: want a format? Specify it and show an example.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"What is few-shot prompting?","difficulty":"Foundational","topic":"Prompt Engineering (System & User Prompts)","objective":"2.1","options":{"A":"Sending only a few tokens per request to save money","B":"Fine-tuning the model on a few thousand examples","C":"Including a few worked examples in the prompt","D":"Calling the model several times and picking an answer at random"},"answer":"C","explanation":"Few-shot prompting includes a handful of examples in the prompt so the model can imitate the desired pattern without retraining. (A) Wrong — limiting tokens is a cost setting. (B) Wrong — fine-tuning changes the model with training data. (D) Wrong — that is repeated sampling, not few-shot prompting. Exam clue: examples inside the prompt = few-shot.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"What does an app need in order to call a model deployed in Microsoft Foundry?","difficulty":"Exam Level","topic":"Deploying Models in the Foundry Portal","objective":"2.1","options":{"A":"Only the dataset that the model was originally trained on","B":"A copy of the model weights stored in the app","C":"The endpoint, a key or token, and the deployment name","D":"The developer's personal sign-in password"},"answer":"C","explanation":"An app sends requests to the resource endpoint, authenticates with a key or Microsoft Entra token, and names the deployment to use. (A) Wrong — training data is not needed to call a deployed model. (B) Wrong — the model is hosted by Azure, not shipped inside the app. (D) Wrong — apps authenticate with keys or tokens, never by sharing a person's password. Memory: endpoint + credential + deployment name.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A team wants to try a newer model version without disrupting the app that uses the current deployment. What is a sensible approach?","difficulty":"Hard","topic":"Deploying Models in the Foundry Portal","objective":"2.1","options":{"A":"Deploy the new version separately and test it first","B":"Delete the current deployment first, then deploy the new one","C":"Type the new version number into the system message","D":"Raise the temperature on the current deployment"},"answer":"A","explanation":"A second deployment lets the team evaluate the new version safely and then point the app at it. (B) Wrong — deleting first takes the app offline. (C) Wrong — the system message steers behaviour; it cannot change the model. (D) Wrong — temperature changes randomness, not the model version. Exam clue: test a new version safely = separate deployment, then switch.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A chat app sends this message list:\n\nmessages = [\n    {\"role\": \"system\", \"content\": \"You are a cooking assistant.\"},\n    {\"role\": \"user\", \"content\": \"Suggest a pasta dish.\"},\n    {\"role\": \"assistant\", \"content\": \"Try carbonara.\"},\n    {\"role\": \"user\", \"content\": \"Is it vegetarian?\"}\n]\n\nWhy does it include the earlier assistant reply?","difficulty":"Exam Level","topic":"Foundry SDK Chat Clients","objective":"2.1","options":{"A":"Because every request must contain exactly four messages","B":"To tell the service which deployment to use","C":"To set the temperature for this request","D":"So the model has the history for the follow-up"},"answer":"D","explanation":"Chat requests carry earlier turns so the model knows what 'it' refers to in the follow-up question. (A) Wrong — there is no fixed message count. (B) Wrong — the deployment is chosen by the model argument. (C) Wrong — temperature is a separate parameter. Memory: the model only knows what you send, so send the history.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A Python app loads its settings like this:\n\nendpoint = os.environ[\"AZURE_AI_ENDPOINT\"]\nkey = os.environ[\"AZURE_AI_KEY\"]\n\nWhy is this better than writing the key directly in the code?","difficulty":"Foundational","topic":"Foundry SDK Chat Clients","objective":"2.1","options":{"A":"It makes the model respond faster","B":"It keeps the secret out of source code","C":"Python cannot read keys written in the code","D":"It lowers the cost of each request"},"answer":"B","explanation":"Reading keys from environment variables (or a key vault) stops secrets being committed and shared with the code. (A) Wrong — where the key is stored has no effect on response speed. (C) Wrong — Python can read literal strings; it is simply unsafe. (D) Wrong — storage of the key does not change pricing. Exam clue: never hard-code keys; load them from configuration or a vault.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A Microsoft Foundry agent must answer questions from the company's product manuals. What should be added to it?","difficulty":"Exam Level","topic":"Building Single Agents in Foundry","objective":"2.1","options":{"A":"A higher temperature setting","B":"A knowledge source, such as file search over the manuals","C":"A second system message telling the agent to be more accurate","D":"A larger max tokens value"},"answer":"B","explanation":"Connecting the manuals as a knowledge tool lets the agent retrieve and ground its answers in them. (A) Wrong — temperature changes randomness, not what the agent knows. (C) Wrong — instructions guide behaviour but don't give the agent the manuals' contents. (D) Wrong — max tokens only allows longer answers. Memory: agent needs your documents = add a knowledge tool.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Where is the BEST place to try out a new single agent before building a client app?","difficulty":"Foundational","topic":"Building Single Agents in Foundry","objective":"2.1","options":{"A":"The Azure Cost Management blade","B":"The folder in the storage account that holds training data","C":"The licence page in the model catalog","D":"The agent playground in the Microsoft Foundry portal"},"answer":"D","explanation":"The portal's playground lets you chat with an agent and adjust its instructions and tools without code. (A) Wrong — Cost Management tracks spending. (B) Wrong — training data is not an interactive test surface. (C) Wrong — licence pages describe terms of use. Exam clue: test without code = playground.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A lightweight client app sends a user's message to a Microsoft Foundry agent. What does it do next to get the answer?","difficulty":"Exam Level","topic":"Agent Client Apps","objective":"2.1","options":{"A":"Ask the agent to respond, then read its output","B":"Train a new model on the user's message","C":"Redeploy the agent for every new message","D":"Delete the conversation and then start a brand-new one"},"answer":"A","explanation":"A client adds the message to the conversation, asks the agent to process it, and then reads the response the agent produces. (B) Wrong — agents use deployed models; client apps do not train models. (C) Wrong — agents are created once and reused. (D) Wrong — that would lose the history the agent needs. Memory: add message → request the agent's response → read its output.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Why should an agent client app check that the agent's response has completed before showing it?","difficulty":"Hard","topic":"Agent Client Apps","objective":"2.1","options":{"A":"Agents only respond after the app restarts","B":"Checking the status changes which model the agent uses","C":"The response can fail or stop before it finishes","D":"It makes the reply more creative"},"answer":"C","explanation":"A response may complete, fail or stop early, for example while waiting on a tool call, so checking its status lets the app react correctly. (A) Wrong — agents respond within the running app. (B) Wrong — status checks don't change configuration. (D) Wrong — run status has no effect on the wording of replies. Exam clue: always handle failed or incomplete responses.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"An app must work out which language each incoming support ticket is written in before routing it. Which Azure Language feature fits?","difficulty":"Foundational","topic":"Text Analysis Apps in Foundry","objective":"2.2","options":{"A":"Key phrase extraction","B":"Sentiment analysis","C":"Language detection","D":"Summarization"},"answer":"C","explanation":"Language detection identifies the language a piece of text is written in. (A) Wrong — key phrase extraction finds the main topics. (B) Wrong — sentiment analysis judges opinion. (D) Wrong — summarization shortens text. Exam clue: which language is this = language detection.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A developer wants text to speech output with a particular pace, pauses and emphasis. What can they use with Azure Speech?","difficulty":"Exam Level","topic":"Speech Apps with Azure Speech","objective":"2.2","options":{"A":"Speech Synthesis Markup Language (SSML)","B":"A JSON field schema for the voice output","C":"A higher model temperature","D":"Key phrase extraction"},"answer":"A","explanation":"SSML is markup that controls how synthesised speech sounds, including rate, pauses and emphasis. (B) Wrong — field schemas define extraction output in Content Understanding. (C) Wrong — temperature controls text randomness, not voice delivery. (D) Wrong — key phrase extraction analyses text and produces no audio. Memory: shape how the voice sounds = SSML.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A meeting app must show captions while people are still speaking. Which Azure Speech capability fits?","difficulty":"Exam Level","topic":"Speech Apps with Azure Speech","objective":"2.2","options":{"A":"Batch transcription after the meeting is uploaded","B":"Text to speech","C":"Custom voice","D":"Real-time speech to text"},"answer":"D","explanation":"Real-time speech to text transcribes audio as it streams in, which is what live captions need. (A) Wrong — batch transcription processes recordings later, not live. (B) Wrong — text to speech produces audio, not captions. (C) Wrong — a custom voice is for synthesised speech output. Exam clue: live captions = real-time speech to text; recorded files = batch.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A team could send spoken questions straight to a multimodal model. When might they still transcribe the audio with speech to text first?","difficulty":"Hard","topic":"Spoken Prompts with Multimodal Models","objective":"2.2","options":{"A":"When they want the answer to be guaranteed correct","B":"When they also need a stored written transcript","C":"When the model must produce an image instead of text","D":"When they want to avoid deploying any model at all"},"answer":"B","explanation":"Transcribing first produces text the team can store, search or audit, which a direct audio prompt does not give them. (A) Wrong — transcribing first does not guarantee a correct answer. (C) Wrong — image generation has nothing to do with transcription. (D) Wrong — a model is still needed to answer the question. Exam clue: need a written record of what was said = transcribe with speech to text.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A developer sends this user message:\n\n{\"role\": \"user\", \"content\": [\n    {\"type\": \"text\", \"text\": \"What fault does this meter show?\"},\n    {\"type\": \"image_url\", \"image_url\": {\"url\": image_url}}\n]}\n\nWhat kind of deployment must handle the request?","difficulty":"Exam Level","topic":"Visual Input with Multimodal Models","objective":"2.3","options":{"A":"An embeddings model that converts the image to a vector","B":"A multimodal model that accepts image input","C":"A text to speech voice","D":"A speech to text model"},"answer":"B","explanation":"The message combines text and an image, so it needs a model deployment that can process images alongside text. (A) Wrong — embeddings models return vectors and do not answer questions about images. (C) Wrong — text to speech produces audio. (D) Wrong — speech to text transcribes audio. Memory: image content in the user message = multimodal model.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Which task suits a multimodal model's visual input BEST?","difficulty":"Foundational","topic":"Visual Input with Multimodal Models","objective":"2.3","options":{"A":"Turning a long paragraph of text into natural speech","B":"Converting a recording into captions","C":"Detecting the language of an email","D":"Answering questions about what a photo shows"},"answer":"D","explanation":"Multimodal models can interpret an image and reason about it in natural language. (A) Wrong — that is text to speech. (B) Wrong — that is speech to text. (C) Wrong — that is language detection. Exam clue: reason about a picture in words = multimodal visual input.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A marketing team generates product images with an AI model. Which practice matters MOST before publishing them?","difficulty":"Exam Level","topic":"Image Generation with Generative Models","objective":"2.3","options":{"A":"Reviewing them for harmful content","B":"Raising the max tokens setting for the image request","C":"Removing the prompt from the request","D":"Switching to a speech model"},"answer":"A","explanation":"Generated images can contain harmful or misleading content, so human review plus guardrails (content filters) is a key responsible AI step. (B) Wrong — max tokens limits text length and does nothing for image safety. (C) Wrong — an image model needs the prompt to generate anything. (D) Wrong — a speech model cannot create or check images. Memory: generated content still needs review before it goes public.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A website needs generated banner images at a specific width and height. Where is this usually set?","difficulty":"Exam Level","topic":"Image Generation with Generative Models","objective":"2.3","options":{"A":"In the system message of a chat model","B":"In the max tokens value of the request","C":"In the size setting of the image generation request","D":"In the Azure region chosen for the resource"},"answer":"C","explanation":"Image generation requests take a size parameter alongside the prompt, so the output matches the dimensions needed. (A) Wrong — a chat model's system message does not control image dimensions. (B) Wrong — max tokens limits text length, not image size. (D) Wrong — the region sets where the model runs, not what it outputs. Exam clue: what to draw = prompt; how big = size setting.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A vision app uses a multimodal model to read expiry dates from photos of food packaging. What should each request contain?","difficulty":"Exam Level","topic":"Vision Apps in Foundry","objective":"2.3","options":{"A":"Only the instruction, with no photo attached","B":"Only the photo, with no instruction or answer format","C":"The photo plus a clear instruction and format","D":"The photo converted into speech first"},"answer":"C","explanation":"Sending the image with a precise instruction and format tells the model what to look for and how to answer. (A) Wrong — without the image there is nothing to read. (B) Wrong — the model may describe the photo rather than return the date. (D) Wrong — turning the photo into audio adds a step and loses the text the model needs to read. Memory: image + clear instruction + output format.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"Why might a vision app ask a multimodal model to return its answer as JSON?","difficulty":"Hard","topic":"Vision Apps in Foundry","objective":"2.3","options":{"A":"So code can read the values reliably","B":"So the model can see higher-resolution images","C":"Because JSON makes answers more creative","D":"So the image is stored inside the model"},"answer":"A","explanation":"A structured format makes the model's answer predictable for code to read. (B) Wrong — output format does not affect image resolution. (C) Wrong — format has nothing to do with creativity. (D) Wrong — sending an image doesn't add it to the model; its weights don't change per request. Exam clue: code needs to read the answer = ask for structured output.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"What does Azure Content Understanding return for a document analysed with a custom field schema?","difficulty":"Exam Level","topic":"Content Understanding: Documents & Forms","objective":"2.4","options":{"A":"A newly generated image of the document","B":"An audio recording of the document read aloud","C":"A sentiment score and nothing else","D":"Structured fields matching the schema"},"answer":"D","explanation":"The analyzer extracts the fields defined in the schema and returns them as structured data. (A) Wrong — Content Understanding extracts information; it does not create images. (B) Wrong — audio output is text to speech. (C) Wrong — sentiment is a text analysis feature, not schema extraction. Memory: schema in, matching structured fields out.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A bank receives loan application forms in many different layouts. Why is Content Understanding a good fit?","difficulty":"Hard","topic":"Content Understanding: Documents & Forms","objective":"2.4","options":{"A":"It works only when every form uses the same layout","B":"It finds the defined fields across layouts","C":"It converts the forms into speech","D":"It generates new forms to send to customers"},"answer":"B","explanation":"Content Understanding uses the field definitions rather than fixed positions, so it can handle varied layouts. (A) Wrong — handling varied layouts is one of its strengths. (C) Wrong — speech output is text to speech. (D) Wrong — generating forms is not its purpose. Exam clue: varied documents, same fields needed = Content Understanding.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A retailer wants product details extracted from photos of shelf labels into structured fields. Which Foundry tool fits?","difficulty":"Exam Level","topic":"Content Understanding: Images, Audio & Video","objective":"2.4","options":{"A":"Azure Speech text to speech","B":"Azure Content Understanding analysing the images","C":"An embeddings model on its own, with no extraction","D":"Azure Language language detection"},"answer":"B","explanation":"Content Understanding can extract defined fields from images as well as documents. (A) Wrong — text to speech produces audio. (C) Wrong — embeddings support search, not field extraction. (D) Wrong — language detection only names the language. Memory: fields from images = Content Understanding.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"A support team wants call recordings turned into structured data: the caller's intent, the product mentioned and the outcome. What should they use?","difficulty":"Hard","topic":"Content Understanding: Images, Audio & Video","objective":"2.4","options":{"A":"Image generation for each call","B":"Text to speech for each call","C":"A small text-only chat model that has no audio input","D":"Content Understanding analysing the audio recordings"},"answer":"D","explanation":"Content Understanding can analyse audio and return the fields you define, such as intent, product and outcome. (A) Wrong — image generation creates pictures. (B) Wrong — text to speech produces audio rather than analysing it. (C) Wrong — a text-only model cannot process the recordings. Exam clue: structured fields from audio = Content Understanding.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"In an extraction app, what should happen when Content Understanding returns a field with low confidence?","difficulty":"Exam Level","topic":"Information Extraction Apps","objective":"2.4","options":{"A":"Flag it for a person to review before it is used","B":"Always discard the whole document","C":"Raise the model temperature and then retry the analysis","D":"Convert the value to speech"},"answer":"A","explanation":"A low confidence score means the value may be wrong, so routing it to human review protects data quality. (B) Wrong — discarding everything wastes the fields that were extracted confidently. (C) Wrong — temperature is a chat setting and doesn't fix extraction confidence. (D) Wrong — speech output does nothing to check the value. Memory: low confidence = human in the loop.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"mcq","question":"An extraction app receives this simplified result:\n\n{\"fields\": {\"InvoiceTotal\": {\"type\": \"number\", \"valueNumber\": 412.5, \"confidence\": 0.97}}}\n\nWhat does 0.97 tell the app?","difficulty":"Exam Level","topic":"Information Extraction Apps","objective":"2.4","options":{"A":"The invoice total after tax","B":"The share of the whole document that the analyzer read","C":"How confident the analyzer is in the extracted value","D":"The temperature used by the model"},"answer":"C","explanation":"The confidence score, between 0 and 1, shows how sure the analyzer is that the value is right. (A) Wrong — the total is the valueNumber field. (B) Wrong — confidence is per field, not a coverage measure. (D) Wrong — temperature is a chat setting and is not reported here. Exam clue: confidence near 1 = high certainty; low values need review.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"multi-select","question":"(Choose TWO) Which TWO mitigations can a team apply to reduce harmful output from a generative AI app?","difficulty":"Exam Level","topic":"Applying Responsible AI","objective":"1.1","options":{"A":"Raising the temperature for more variety","B":"Guardrails (content filters) on prompts and responses","C":"Removing all logging and monitoring","D":"A system message that sets safe behaviour and scope","E":"Publishing the app without any sign-in"},"answers":["B","D"],"explanation":"Guardrails (previously called content filters) screen harmful prompts and responses in the safety system layer, and a system message sets the app's scope and safe behaviour in the system message layer. (A) Wrong — higher temperature increases randomness and can make output less predictable. (C) Wrong — logging and monitoring are how teams spot and fix harms. (E) Wrong — removing sign-in reduces control and accountability. Exam clue: guardrails (safety system layer) + a well-written system message (system message layer).","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"},
    {"type":"multi-select","question":"(Choose TWO) A compliance app must find people's names in transcripts and redact personal details. Which TWO Azure Language features help?","difficulty":"Exam Level","topic":"Text Analysis Apps in Foundry","objective":"2.2","options":{"A":"Text to speech","B":"Language detection","C":"Named entity recognition","D":"Image generation","E":"PII detection"},"answers":["C","E"],"explanation":"Named entity recognition finds people and other named items, and PII detection identifies and can redact personal details. (A) Wrong — text to speech produces audio. (B) Wrong — language detection only names the language. (D) Wrong — image generation creates pictures. Memory: find names = NER; find and redact personal data = PII detection.","source":"curated-ai901-p3a","addedVersion":"8.123.0","addedDate":"2026-10-08"}
  ]
};
