// Shared production-true sample data for the Progress page mockups.
// 50 real Network+ (N10-009) topics across the 5 official domains.
// Each mockup inlines or imports this so the founder compares identical data.
window.PROGRESS_DATA = {
  "summary": { "total": 50, "weak": 18, "untouched": 10, "strong": 10, "developing": 12, "coverage": 80, "avgMastery": 38 },
  "domains": [
    { "key": "concepts", "label": "Networking Concepts", "weight": 23, "obj": "1.0", "count": 13, "avgMastery": 32 },
    { "key": "implementation", "label": "Network Implementation", "weight": 20, "obj": "2.0", "count": 13, "avgMastery": 50 },
    { "key": "operations", "label": "Network Operations", "weight": 19, "obj": "3.0", "count": 7, "avgMastery": 28 },
    { "key": "security", "label": "Network Security", "weight": 14, "obj": "4.0", "count": 11, "avgMastery": 35 },
    { "key": "troubleshooting", "label": "Network Troubleshooting", "weight": 24, "obj": "5.0", "count": 6, "avgMastery": 45 }
  ],
  "recommendation": { "name": "Network Models & OSI", "domainLabel": "Networking Concepts", "mastery": 0, "reason": "Highest leverage: heavy exam weight, low mastery" },
  "topics": [
    { "name": "Network Models & OSI", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "TCP/IP Basics", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 20, "accuracy": 21, "attempts": 19, "lastSeenDays": 34, "status": "weak" },
    { "name": "Subnetting & IP Addressing", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 88, "accuracy": 76, "attempts": 35, "lastSeenDays": 21, "status": "strong" },
    { "name": "TCP/IP Applications", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 48, "accuracy": 38, "attempts": 9, "lastSeenDays": 2, "status": "developing" },
    { "name": "Network Naming (DNS & DHCP)", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 57, "accuracy": 58, "attempts": 40, "lastSeenDays": 5, "status": "developing" },
    { "name": "IPv6", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 30, "accuracy": 21, "attempts": 18, "lastSeenDays": 21, "status": "weak" },
    { "name": "NAT & IP Services", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "NTP, ICMP & Traffic Types", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "Port Numbers", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 95, "accuracy": 73, "attempts": 22, "lastSeenDays": 2, "status": "strong" },
    { "name": "Virtualisation & Cloud", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 47, "accuracy": 49, "attempts": 6, "lastSeenDays": 1, "status": "developing" },
    { "name": "Cloud Networking & VPCs", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 9, "accuracy": 20, "attempts": 16, "lastSeenDays": 5, "status": "weak" },
    { "name": "Network Appliances & Device Functions", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 15, "accuracy": 22, "attempts": 22, "lastSeenDays": 8, "status": "weak" },
    { "name": "DNS Records & DNSSEC", "domain": "concepts", "domainLabel": "Networking Concepts", "obj": "1.0", "mastery": 10, "accuracy": 20, "attempts": 18, "lastSeenDays": 5, "status": "weak" },
    { "name": "Routing Protocols", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 85, "accuracy": 62, "attempts": 20, "lastSeenDays": 1, "status": "strong" },
    { "name": "OSPF", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 18, "accuracy": 20, "attempts": 5, "lastSeenDays": 13, "status": "weak" },
    { "name": "BGP", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 27, "accuracy": 23, "attempts": 30, "lastSeenDays": 21, "status": "weak" },
    { "name": "Switch Features & VLANs", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 6, "accuracy": 20, "attempts": 18, "lastSeenDays": 8, "status": "weak" },
    { "name": "VLAN Trunking", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 77, "accuracy": 55, "attempts": 30, "lastSeenDays": 2, "status": "strong" },
    { "name": "STP/RSTP", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 57, "accuracy": 37, "attempts": 32, "lastSeenDays": 2, "status": "developing" },
    { "name": "Wireless Networking", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "Ethernet Basics", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 22, "accuracy": 26, "attempts": 25, "lastSeenDays": 2, "status": "weak" },
    { "name": "Ethernet Standards", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 73, "accuracy": 53, "attempts": 40, "lastSeenDays": 2, "status": "developing" },
    { "name": "Cabling & Topology", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 47, "accuracy": 25, "attempts": 34, "lastSeenDays": 13, "status": "developing" },
    { "name": "Integrating Networked Devices", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 76, "accuracy": 60, "attempts": 11, "lastSeenDays": 2, "status": "strong" },
    { "name": "SDN, NFV & Automation", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 60, "accuracy": 57, "attempts": 7, "lastSeenDays": 21, "status": "developing" },
    { "name": "Data Center Architectures", "domain": "implementation", "domainLabel": "Network Implementation", "obj": "2.0", "mastery": 99, "accuracy": 97, "attempts": 14, "lastSeenDays": 8, "status": "strong" },
    { "name": "Network Operations", "domain": "operations", "domainLabel": "Network Operations", "obj": "3.0", "mastery": 38, "accuracy": 38, "attempts": 9, "lastSeenDays": 13, "status": "weak" },
    { "name": "Data Centres", "domain": "operations", "domainLabel": "Network Operations", "obj": "3.0", "mastery": 17, "accuracy": 20, "attempts": 13, "lastSeenDays": 34, "status": "weak" },
    { "name": "WAN Connectivity", "domain": "operations", "domainLabel": "Network Operations", "obj": "3.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "SD-WAN & SASE", "domain": "operations", "domainLabel": "Network Operations", "obj": "3.0", "mastery": 42, "accuracy": 20, "attempts": 37, "lastSeenDays": 2, "status": "developing" },
    { "name": "SMB & Network File Services", "domain": "operations", "domainLabel": "Network Operations", "obj": "3.0", "mastery": 62, "accuracy": 46, "attempts": 41, "lastSeenDays": 34, "status": "developing" },
    { "name": "Business Continuity & Disaster Recovery", "domain": "operations", "domainLabel": "Network Operations", "obj": "3.0", "mastery": 38, "accuracy": 22, "attempts": 29, "lastSeenDays": 5, "status": "weak" },
    { "name": "Network Monitoring & Observability", "domain": "operations", "domainLabel": "Network Operations", "obj": "3.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "Securing TCP/IP", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 28, "accuracy": 27, "attempts": 28, "lastSeenDays": 2, "status": "weak" },
    { "name": "Protecting Networks", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 37, "accuracy": 38, "attempts": 13, "lastSeenDays": 1, "status": "weak" },
    { "name": "AAA & Authentication", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 89, "accuracy": 68, "attempts": 36, "lastSeenDays": 34, "status": "strong" },
    { "name": "IPsec & VPN Protocols", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 59, "accuracy": 39, "attempts": 42, "lastSeenDays": 5, "status": "developing" },
    { "name": "IPsec VPN", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "SSL/TLS VPN", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "PKI & Certificate Management", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 44, "accuracy": 34, "attempts": 19, "lastSeenDays": 8, "status": "developing" },
    { "name": "Firewalls, DMZ & Security Zones", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 95, "accuracy": 92, "attempts": 10, "lastSeenDays": 1, "status": "strong" },
    { "name": "WPA3 & EAP Authentication", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "Network Attacks & Threats", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 36, "accuracy": 20, "attempts": 19, "lastSeenDays": 34, "status": "weak" },
    { "name": "Physical Security Controls", "domain": "security", "domainLabel": "Network Security", "obj": "4.0", "mastery": 0, "accuracy": 0, "attempts": 0, "lastSeenDays": null, "status": "untouched" },
    { "name": "Network Troubleshooting & Tools", "domain": "troubleshooting", "domainLabel": "Network Troubleshooting", "obj": "5.0", "mastery": 81, "accuracy": 81, "attempts": 12, "lastSeenDays": 1, "status": "strong" },
    { "name": "Cable Issues", "domain": "troubleshooting", "domainLabel": "Network Troubleshooting", "obj": "5.0", "mastery": 22, "accuracy": 20, "attempts": 8, "lastSeenDays": 1, "status": "weak" },
    { "name": "Service Issues", "domain": "troubleshooting", "domainLabel": "Network Troubleshooting", "obj": "5.0", "mastery": 41, "accuracy": 48, "attempts": 32, "lastSeenDays": 21, "status": "developing" },
    { "name": "Perf Issues", "domain": "troubleshooting", "domainLabel": "Network Troubleshooting", "obj": "5.0", "mastery": 89, "accuracy": 86, "attempts": 12, "lastSeenDays": 5, "status": "strong" },
    { "name": "Connection Issues", "domain": "troubleshooting", "domainLabel": "Network Troubleshooting", "obj": "5.0", "mastery": 16, "accuracy": 20, "attempts": 39, "lastSeenDays": 34, "status": "weak" },
    { "name": "CompTIA Troubleshooting Methodology", "domain": "troubleshooting", "domainLabel": "Network Troubleshooting", "obj": "5.0", "mastery": 22, "accuracy": 20, "attempts": 21, "lastSeenDays": 13, "status": "weak" }
  ]
};
